from pathlib import Path
import re

# archivos
template = Path("template.html")
pydoc_html = Path("utils.html")
output = Path("index.html")

# leer contenidos
tpl = template.read_text(encoding="utf8")
doc = pydoc_html.read_text(encoding="utf8")

# extraer solo la sección de funciones de pydoc
match = re.search(
    r'<table class="section">.*?<strong class="bigsection">Functions</strong>.*?</table>',
    doc,
    re.S
)

if not match:
    raise RuntimeError("No se encontró la sección Functions")

functions_html = match.group(0)

# reemplazar en template
result = re.sub(
    r'<!-- AUTOGENERATED:START -->.*?<!-- AUTOGENERATED:END -->',
    f'<!-- AUTOGENERATED:START -->\n{functions_html}\n<!-- AUTOGENERATED:END -->',
    tpl,
    flags=re.S
)

# guardar
output.write_text(result, encoding="utf8")
