name = "MMfem"
uuid = "bff6db78-1b9c-4457-9493-85718d7bddaf"
authors = ["Mauricio Mendiluce <mauricio.mendiluce@gmail.com>"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DelaunayTriangulation = "927a84f5-c5f4-47a5-9785-b46e178433df"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
CairoMakie = "0.12.18"
DelaunayTriangulation = "1.6.3"
LinearAlgebra = "1.11.0"
LinearSolve = "2.38.0"
Plots = "1.40.9"
SparseArrays = "1.11.0"
